# Generated by Django 4.1.4 on 2022-12-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
    ]
